name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
defaults:
  run:
    working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
          npm run build
      - name: Install playwright browsers
        run: |
          npx playwright install chromium --with-deps
          npx playwright install firefox --with-deps
          npx playwright install webkit --with-deps
      - name: Run tests
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run: npm run test:coverage && npm run test:e2e
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
